parameters:
  module_model.class: modules\cover\model\Module
  module_result_set.class: Zend\Db\ResultSet\HydratingResultSet
  module_table_gateway.class: Zend\Db\TableGateway\TableGateway
  module_table.class: modules\cover\model\ModuleTable

services:
  module_model:
    class: "%module_model.class%"
  module_result_set:
    class: "%module_result_set.class%"
    arguments: ["@object_prop_hydrator", "@module_model"]
  module_table_gateway:
    class: "%module_table_gateway.class%"
    arguments:
      - modules
      - "@adapter"
      - []
      - "@module_result_set"
  module_table:
    class: "%module_table.class%"
    arguments: ["@module_table_gateway", module_code]

  module.form.type:
            class: modules\cover\form\ModuleType
            tags:
                - { name: form.type, alias: module }
