tools:
  php_sim: true
  php_pdepend: true
  php_analyzer: true

filter:
  excluded_paths:
    - 'tests/*'
    - 'lib/Zend/*'
    - 'vendor/*'
    - 'lib/Maketok/App/Test/*'
    - 'lib/Maketok/Installer/Ddl/Test/*'
    - 'lib/Maketok/Util/Test/*'
    - 'lib/Maketok/Template/Navigation/Test/*'

tools:
    external_code_coverage:
        timeout: 600
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["lib/*"]
            excluded_paths: ["lib/Zend/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["docs", "examples", "tests", "vendor", 'Test', 'var']
        excluded_paths: ["lib/Zend/*"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["lib/*"]
            excluded_paths: ["lib/Zend/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["docs", "examples", "tests", "vendor", 'Test', 'var']
        excluded_paths: ["lib/Zend/*"]
    php_mess_detector:
        enabled: true
        config:
            ruleset: phpmd.xml.dist
            design_rules: { eval_expression: false }
        filter:
            paths: ["lib/*"]
            excluded_paths: ["lib/Zend/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["docs", "examples", "tests", "vendor", 'Test', 'var']
        excluded_paths: ["lib/Zend/*"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["lib/*"]
            excluded_paths: ["lib/Zend/*"]
    php_hhvm:
        enabled: true
        filter:
            paths: ["lib/*"]
            excluded_paths: ["lib/Zend/*"]
    sensiolabs_security_checker: true
