tools:
  php_sim: true
  php_pdepend: true
  php_analyzer: true

filter:
  excluded_paths:
    - 'lib/Zend/*'

tools:
    external_code_coverage:
        timeout: 600
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["lib/Maketok/*", "modules/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["docs", "examples", "tests", "vendor", 'Test', 'var']
    php_cs_fixer:
        enabled: true
        config:
            level: psr2
        filter:
            paths: ["lib/Maketok/*", "modules/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["docs", "examples", "tests", "vendor", 'Test', 'var']
    php_mess_detector:
        enabled: true
        config:
            ruleset: phpmd.xml.dist
            design_rules: { eval_expression: false }
        filter:
            paths: ["lib/Maketok/*", "modules/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["docs", "examples", "tests", "vendor", 'Test', 'var']
    php_analyzer:
        enabled: true
        filter:
            paths: ["lib/Maketok/*", "modules/*"]
    php_hhvm:
        enabled: true
        filter:
            paths: ["lib/Maketok/*", "modules/*"]
    sensiolabs_security_checker: true
