language: php

php:
  - "5.5"
  - "5.4"

install: composer install --dev

before_script:
  - cp config/local.php.sample config/local.php

script:
  - cd tests; ../vendor/bin/phpunit --testsuite Util Test Suite
  - ../vendor/bin/phpunit --testsuite Installer Test Suite

notifications:
  email: true

matrix:
  fast_finish: true