language: php

php:
  - "5.6"
  - "5.5"
  - "5.4"

install: composer install --dev

before_script:
  - mysql -e 'create database site_test;'

script:
  - cd tests
  - ../vendor/bin/phpunit --bootstrap ./ci/travis.bootstrap.php --testsuite "util" --report-useless-tests --strict
  - ../vendor/bin/phpunit --bootstrap ./ci/travis.bootstrap.php --testsuite "installer" --report-useless-tests --strict
  - ../vendor/bin/phpunit --bootstrap ./ci/travis.bootstrap.php --testsuite "app" --report-useless-tests --strict
  - ../vendor/bin/phpunit --bootstrap ./ci/travis.bootstrap.php --testsuite "nav" --report-useless-tests --strict
  - ../vendor/bin/phpunit --bootstrap ./ci/travis.bootstrap.php --report-useless-tests --coverage-clover ./coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./coverage.clover

notifications:
  email: true

matrix:
  fast_finish: true
