language: php

php:
  - "5.5"
  - "5.4"

install: composer install --dev

before_script:
  - cp config/local.php.sample config/local.php
  - mysql -e 'create database site_test;'
  - cp config/travis.services.yml config/dev.services.yml

script:
  - cd tests; ../vendor/bin/phpunit --testsuite "Util Test Suite"
  - ../vendor/bin/phpunit --testsuite "Installer Test Suite"

notifications:
  email: true

matrix:
  fast_finish: true
