language: php

php:
  - "5.5"
  - "5.4"

install: composer install --dev

before_script:
  - cp config/local.php.sample config/local.php
  - mysql -e 'create database site_test;'
  - yes | \cp -rf config/travis.services.yml config/test.services.yml

script:
  - cd tests; ../vendor/bin/phpunit --testsuite "util"
  - ../vendor/bin/phpunit --testsuite "installer"

notifications:
  email: true

matrix:
  fast_finish: true
