language: php

php:
  - "5.6"
  - "5.5"
  - "5.4"

install: composer install --dev

before_script:
  - cp config/local.php.sample config/local.php
  - mysql -e 'create database site_test;'
#  - yes | \cp -f config/di/travis.services.yml config/di/test.services.yml
  - yes | \cp -f config/di/travis.parameters.yml config/di/test.parameters.yml

script:
  - cd tests
  - ../vendor/bin/phpunit --testsuite "util" --report-useless-tests --strict --exclude-group=Coverage
  - ../vendor/bin/phpunit --testsuite "installer" --report-useless-tests --strict --exclude-group=Coverage
  - ../vendor/bin/phpunit --testsuite "app" --report-useless-tests --strict --exclude-group=Coverage
  - ../vendor/bin/phpunit --testsuite "nav" --report-useless-tests --strict --exclude-group=Coverage
  - ../vendor/bin/phpunit --report-useless-tests --coverage-clover=coverage.clover --group=Coverage

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./coverage.clover

notifications:
  email: true

matrix:
  fast_finish: true
