# This is a part of Maketok site package.
# @author Oleg Kulik <slayer.birden@gmail.com>
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
  article_model.class: modules\blog\Model\Article
  article_result_set.class: Zend\Db\ResultSet\HydratingResultSet
  article_table_gateway.class: Zend\Db\TableGateway\TableGateway
  article_table.class: modules\blog\Model\ArticleTable
