# This is a part of Maketok Site. Licensed under GPL 3.0
# @project site
# @developer Oleg Kulik slayer.birden@gmail.com maketok.com

parameters:
  article_model.class: modules\blog\model\Article
  article_result_set.class: Zend\Db\ResultSet\HydratingResultSet
  article_table_gateway.class: Zend\Db\TableGateway\TableGateway
  article_table.class: modules\blog\model\ArticleTable
