# This is a part of Maketok site package.
# @author Oleg Kulik <slayer.birden@gmail.com>
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
  article_model:
    class: "%article_model.class%"

  article_result_set:
    class: "%article_result_set.class%"
    arguments: ["@object_prop_hydrator", "@article_model"]

  article_table_gateway:
    class: "%article_table_gateway.class%"
    arguments:
      - blog_article
      - "@adapter"
      - []
      - "@article_result_set"

  article_table:
    class: "%article_table.class%"
    arguments: ["@article_table_gateway", id, id]

  article.form.type:
          class: modules\blog\Form\ArticleType
          tags:
              - { name: form.type, alias: article }

  md_parser_engine:
    class: modules\blog\Util\Markdown\Engine

  twig_extension_md:
    class: Aptoma\Twig\Extension\MarkdownExtension
    arguments: ["@md_parser_engine"]
    tags:
      - { name: twig.extension }
