# This is a part of Maketok site package.
# @author Oleg Kulik <slayer.birden@gmail.com>
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
  adapter:
      class: Maketok\Util\MockAdapter

  logger:
      class: Monolog\Logger
      arguments: ["setup_logger", ["@logger_handler"]]

  logger_handler:
      class: Monolog\Handler\StreamHandler
      arguments: ["php://output", 100]
