# This is a part of Maketok Site. Licensed under GPL 3.0
# Please do not use for your own profit.
# @project site
# @developer Slayer slayer.birden@gmail.com maketok.com

parameters:
  module_config_file_name: Config.php
  module_config_name: Config
  defaultFormTheme: form_div_layout.html.twig
  translation_locale: en
  log_dir: "%AR%/var/log/"
  cache_dir: "%AR%/var/cache/"
  hydrating_resultset: Maketok\Util\Zend\Db\ResultSet\HydratingResultSet
