# This is a part of Maketok site package.
# @author Oleg Kulik <slayer.birden@gmail.com>
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
  log_dir: %ar%/var/log/
  cache_dir: %ar%/var/cache/
  hydrating_resultset: Maketok\Util\Zend\Db\ResultSet\HydratingResultSet
  debug: false
