# This is a part of Maketok Site. Licensed under GPL 3.0
# @project site
# @developer Oleg Kulik slayer.birden@gmail.com maketok.com

parameters:
  log_dir: %ar%/var/log/
  cache_dir: %ar%/var/cache/
  hydrating_resultset: Maketok\Util\Zend\Db\ResultSet\HydratingResultSet
  debug: false
