# This is a part of Maketok Site. Licensed under GPL 3.0
# @project site
# @developer Oleg Kulik slayer.birden@gmail.com maketok.com

services:

  adapter:
    class: Zend\Db\Adapter\Adapter
    arguments:
      - driver: "%db_driver%"
        hostname: "%db_host%"
        database: "%db_database%"
        username: "%db_user%"
        password: "%db_passw%"

  directory_handler:
    class: Maketok\Util\DirectoryHandler

  lock_stream_handler:
    class: Maketok\Util\StreamHandler

  subject_manager:
    class: Maketok\Observer\SubjectManager
    factory_class: Maketok\Observer\SubjectManager
    factory_method: getInstance
    calls:
          - [attach, [dispatch, ["@front_controller", dispatch], 10]]
          - [attach, [ioc_container_initialized, ["@module_manager", processModuleConfig], 10]]
          - [attach, [module_list_exists, \Maketok\App\ContainerFactory::serviceContainerProcessModules, 0]]
          - [attach, [ioc_container_initialized, \Maketok\App\ContainerFactory::scCompile, 10]]
          - [attach, [ioc_container_initialized, \Maketok\App\ContainerFactory::scDump, 5]]
          - [attach, [ioc_container_compiled, ["@module_manager", updateModules], 20]]
          - [attach, [ioc_container_compiled, ["@module_manager", processModules], 15]]
          - [attach, [ioc_container_compiled, ["@module_manager", addInstallerSubscribers], 10]]
          - [attach, [response_send_before, ["@site", terminate], 0]]
          - [attach, [noroute_action, ["@site", terminate], 0]]

  object_prop_hydrator:
    class: Maketok\Util\Hydrator\ObjectProperty

  logger_handler:
    class: Maketok\Util\Monolog\Handler\StreamHandler
    arguments: ["%log_dir%site.log", 100]

  logger:
    class: Monolog\Logger
    arguments: ["application_logger", ["@logger_handler"]]

  zend_sql_platform:
    class: Zend\Db\Sql\Platform\Platform
    arguments: ["@adapter"]

  zend_db_sql:
    class: Maketok\Util\Zend\Db\Sql\Sql
    arguments: ["@adapter", ~, "@zend_sql_platform"]

  router:
    class: Maketok\Mvc\Router\Stack

  front_controller:
    class: Maketok\Mvc\Controller\Front
    arguments: ["@router"]

  request:
    synthetic: true

  #main app service
  site:
    synthetic: true
