# This is a part of Maketok site package.
# @author Oleg Kulik <slayer.birden@gmail.com>
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:

  ioc_factory:
    class: Maketok\App\ContainerFactory
    factory: [Maketok\App\ContainerFactory, getInstance]

  adapter:
    class: Zend\Db\Adapter\Adapter
    arguments:
      - driver: "%db_driver%"
        hostname: "%db_host%"
        database: "%db_database%"
        username: "%db_user%"
        password: "%db_passw%"

  directory_handler:
    class: Maketok\Util\DirectoryHandler

  lock_stream_handler:
    class: Maketok\Util\StreamHandler
    scope: prototype

  date_time_strategy:
    class: Maketok\Util\Hydrator\Strategy\DateTimeStrategy

  object_prop_hydrator:
    class: Maketok\Util\Hydrator\ObjectProperty
    calls:
      - [addStrategy, [date, "@date_time_strategy"]]
      - [addStrategy, [created_at, "@date_time_strategy"]]
      - [addStrategy, [updated_at, "@date_time_strategy"]]

  array_string_strategy:
    class: Maketok\Util\Hydrator\Strategy\ArrayStringStrategy

  logger_handler:
    class: Maketok\Util\Monolog\Handler\StreamHandler
    arguments: ["%log_dir%site.log", 100]

  logger:
    class: Monolog\Logger
    arguments: ["application_logger", ["@logger_handler"]]

  zend_db_sql:
    class: Zend\Db\Sql\Sql
    arguments: ["@adapter"]

  config_getter:
    class: Maketok\Util\ConfigGetter

  request:
    synthetic: true

  #main app service
  site:
    synthetic: true
