# This is a part of Maketok Site. Licensed under GPL 3.0
#
# @project site
# @developer Oleg Kulik slayer.birden@gmail.com maketok.com

services:
  test_logger_handler:
    class: Monolog\Handler\TestHandler

  logger:
      class: Monolog\Logger
      arguments: ["application_logger", ["@test_logger_handler"]]
