# This is a part of Maketok site package.
# @author Oleg Kulik <slayer.birden@gmail.com>
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
  test_logger_handler:
    class: Monolog\Handler\TestHandler

  logger:
      class: Monolog\Logger
      arguments: ["application_logger", ["@test_logger_handler"]]
