# This is a part of Maketok Site. Licensed under GPL 3.0
#
# @project site
# @developer Oleg Kulik slayer.birden@gmail.com maketok.com

services:
  test_logger_handler:
    class: Monolog\Handler\TestHandler

  logger:
      class: Monolog\Logger
      arguments: ["application_logger", ["@test_logger_handler"]]

  subject_manager:
    class: Maketok\Observer\SubjectManager
    factory_class: Maketok\Observer\SubjectManager
    factory_method: getInstance
    calls:
          - [attach, [ioc_container_initialized, ["@module_manager", processModuleConfig], 10]]
          - [attach, [module_list_exists, "\Maketok\App\ContainerFactory::serviceContainerProcessModules", 0]]
          - [attach, [ioc_container_initialized, "\Maketok\App\ContainerFactory::scCompile", 10]]
          - [attach, [ioc_container_compiled, ["@module_manager", updateModules], 20]]
          - [attach, [ioc_container_compiled, ["@module_manager", processModules], 15]]
          - [attach, [ioc_container_compiled, ["@module_manager", addInstallerSubscribers], 10]]
