# This is a part of Maketok site package.
# @author Oleg Kulik <slayer.birden@gmail.com>
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
  db_user: travis
  db_passw:
  db_host: localhost
  db_database: site_test
  db_driver: pdo_sqlite
  base_url: http://mysite.com
