# This is a part of Maketok Site. Licensed under GPL 3.0
# Please do not use for your own profit.
# @project site
# @developer Slayer slayer.birden@gmail.com maketok.com

parameters:
  module_config_file_name: Config.php
  module_config_name: Config
  defaultFormTheme: form_div_layout.html.twig
  translation_locale: en
  dll_lock_path: "%AR%%DS%var%DS%locks%DS%ddl_installer.lock"
  log_dir: "%AR%%DS%var%DS%log%DS%"
  cache_dir: "%AR%%DS%var%DS%cache%DS%"

services:
  adapter:
    class: Zend\Db\Adapter\Adapter
    arguments: [{driver: "%db_driver%", hostname: "%db_host%", database: "%db_database%", username: "%db_user%", password: "%db_passw%"}]

  template_engine:
    class: Maketok\Template\Twig
    arguments: ["%debug%"]

  module_manager:
    class: Maketok\Module\ModuleManager
    arguments: ["@adapter"]

  session_save_handler:
    class: Maketok\Http\Session\DbHandler
    arguments: ["@adapter"]

  session_storage:
    class: Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage
    arguments: [[], "@session_save_handler"]

  session_manager:
    class: Symfony\Component\HttpFoundation\Session\Session
    arguments: ["@session_storage"]

  directory_handler:
    class: Maketok\Util\DirectoryHandler

  lock_stream_handler:
    class: Maketok\Util\StreamHandler
    calls:
      - [setPath, ["%dll_lock_path%"]]

  subject_manager:
    class: Maketok\Observer\SubjectManager
    factory_class: Maketok\Observer\SubjectManager
    factory_method: getInstance

  registry:
    class: Maketok\App\Registry
    factory_class: Maketok\App\Registry
    factory_method: getInstance

  object_prop_hydrator:
    class: Zend\Stdlib\Hydrator\ObjectProperty

  default_logger_handler:
    class: Maketok\Util\Monolog\Handler\StreamHandler
    arguments: ["%log_dir%site.log", 100]

  chrome_debug_logger_handler:
    class: Monolog\Handler\ChromePHPHandler

  logger:
    class: Monolog\Logger
    arguments: ["application_logger", ["@=parameter('debug') == true ? service('chrome_debug_logger_handler') : service('default_logger_handler')"]]

  zend_sql_platform:
    class: Maketok\Util\Zend\Db\Sql\Platform\Platform
    arguments: ["@adapter"]

  zend_db_sql:
    class: Maketok\Util\Zend\Db\Sql\Sql
    arguments: ["@adapter", [], "@zend_sql_platform"]

  installer_ddl_resource:
    class: Maketok\Installer\Ddl\ConfigReader
    arguments: ["@adapter"]

  installer_ddl_reader:
    class: Maketok\Installer\Ddl\ConfigReader
    arguments: ["@installer_ddl_resource"]

  installer_ddl_manager:
    class: Maketok\Installer\Ddl\Manager
    arguments:
      - "@adapter"
      - "@zend_db_sql"
      - "@installer_ddl_reader"
      - "@ddl_client_config_table"
      - "@lock_stream_handler"

  router:
    class: Maketok\Mvc\Router\Stack

  front_controller:
    class: Maketok\Mvc\Controller\Front
    arguments: ["@router"]

  form_builder_extension_httpfoundation:
    class: Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationExtension
    tags:
      - { name: form.extension }

  validator_builder:
    class: Symfony\Component\Validator\ValidatorBuilder
    calls:
      - [addYamlMappings, ["@=container.hasParameter('validator_builder.yml.config.paths') ? parameter('validator_builder.yml.config.paths') : []"]]

  validator:
    class: Symfony\Component\Validator\Validator
    factory_service: validator_builder
    factory_method: getValidator

  form_builder_extension_validation:
    class: Symfony\Component\Form\Extension\Validator\ValidatorExtension
    arguments: ["@validator"]
    tags:
      - { name: form.extension }

  form_builder:
    class: Symfony\Component\Form\FormBuilder
    factory_class: Symfony\Component\Form\Forms
    factory_method: createFormFactoryBuilder

  twig_extension_text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension }

  twig_renderer_engine:
    class: Symfony\Bridge\Twig\Form\TwigRendererEngine
    arguments: [["%defaultFormTheme%"]]
    calls:
      - [setEnvironment, ["@twig_env"]]

  twig_renderer:
    class: Symfony\Bridge\Twig\Form\TwigRenderer
    arguments: ["@twig_renderer_engine"]

  twig_extension_form:
    class: Symfony\Bridge\Twig\Extension\FormExtension
    arguments: ["@twig_renderer"]
    tags:
      - { name: twig.extension }

  translator_loader_xliff:
    class: Symfony\Component\Translation\Loader\XliffFileLoader

  translator:
    class: Symfony\Component\Translation\Translator
    arguments: ["%translation_locale%"]
    calls:
      - [addLoader, [xlf, "@translator_loader_xliff"]]
      - [addResource, [xlf, "%AR%%DS%translations%DS%messages.en.xlf", "%translation_locale%"]]

  twig_extension_translation:
    class: Symfony\Bridge\Twig\Extension\TranslationExtension
    arguments: ["@translator"]
    tags:
      - { name: twig.extension }

  twig_extension_debug:
    class: Twig_Extension_Debug
    tags:
      - { name: twig.extension }

  twig_loader:
    class: Twig_Loader_Filesystem
    calls:
      - [addPath, ["%AR%%DS%vendor%DS%symfony%DS%twig-bridge%DS%Symfony%DS%Bridge%DS%Twig%DS%Resources%DS%views%DS%Form"]]
      - [addPath, ["%AR%%DS%lib%DS%Maketok%DS%Template%DS%Resource%DS%view%DS%Form"]]

  twig_env:
    class: Twig_Environment
    arguments:
      - "@twig_loader"
      - { cache: "%AR%%DS%var%DS%cache", debug: "%debug%" }
