modules\blog\model\Article:
  properties:
    title:
      - NotBlank: ~
      - Length:
          min: 2
          max: 200
          minMessage: "Title can not be less than {{ limit }} characters"
          maxMessage: "Title can not be longer than {{ limit }} characters"
    code:
      - NotBlank: ~
      - Regex:
          pattern: "/^[a-zA-Z0-9_.-]+$/"
          message: "Please provide only alphaberical characters plus [_.-]"
      - Length:
          min: 2
          max: 30
          minMessage: "Code can not be less than {{ limit }} characters"
          maxMessage: "Code can not be longer than {{ limit }} characters"
    created_at:
      - DateTime: ~
    content:
      - NotBlank: ~
    author:
      - NotBlank: ~
