# This is a part of Maketok site package.
# @author Oleg Kulik <slayer.birden@gmail.com>
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
  pages_factory:
      class: Maketok\Model\HydratingTableFactory
      arguments:
        - pages
        - id
        - modules\pages\Model\Page
        - id
        - modules\pages\Model\PageTable

  pages_table:
    class: modules\pages\Model\PageTable
    factory: ["@pages_factory", spawnTable]

  page.form.type:
          class: modules\pages\Form\PageType
          tags:
              - { name: form.type, alias: page }
